version: "3.9"

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # backend:
  #   build:
  #     context: ./back
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     SECRET_KEY: ${SECRET_KEY}
  #     NODE_ENV: production
  #   ports:
  #     - "3000:3000"

  # bot:
  #   build:
  #     context: ./bot
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     SECRET_KEY: ${SECRET_KEY}
  #     NODE_ENV: production
  #   ports:
  #     - "4000:4000"

volumes:
  pgdata:
